import http from 'node:http';
import {readFile,writeFile,mkdir,stat,unlink} from 'node:fs/promises';
import {existsSync,readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {join,extname} from 'node:path';
import {randomBytes,scryptSync,timingSafeEqual,createCipheriv,createDecipheriv,createHmac} from 'node:crypto';
import {db,dataDir,uid,row,all,run,publicAccount} from './db.mjs';
import * as x from './x.mjs';
import * as ai from './ai.mjs';
const port=Number(process.env.PORT||3000),host=process.env.HOST||'127.0.0.1';
const secretFile=join(dataDir,'.app-secret');
const secret=process.env.APP_SECRET||(()=>{if(existsSync(secretFile))return readFileSync(secretFile,'utf8');const s=randomBytes(32).toString('hex');writeFileSync(secretFile,s,{mode:0o600,flag:'wx'});return s})();
if(secret.length<32)throw Error('APP_SECRET は32文字以上にしてください');
const passwordFile=join(dataDir,'.admin-password');
const password=process.env.ADMIN_PASSWORD||(()=>{if(existsSync(passwordFile))return readFileSync(passwordFile,'utf8');const p=randomBytes(18).toString('base64url');writeFileSync(passwordFile,p,{mode:0o600,flag:'wx'});console.log(`初期管理パスワード: ${p}`);return p})();
const sessions=new Map(),loginTries=new Map();
const limitLogin=(ip)=>{const now=Date.now(),s=loginTries.get(ip)||{count:0,at:now};if(now-s.at>15*60e3){s.count=0;s.at=now}loginTries.set(ip,s);return s};
function encrypt(value){const iv=randomBytes(12),key=scryptSync(secret,'x-nekama-sessions-v1',32);const c=createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.update(value),c.final(),c.getAuthTag()]).toString('base64')}
function decrypt(value){const bytes=Buffer.from(value,'base64'),key=scryptSync(secret,'x-nekama-sessions-v1',32);const d=createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));d.setAuthTag(bytes.subarray(bytes.length-16));return Buffer.concat([d.update(bytes.subarray(12,-16)),d.final()]).toString()}
const sessionKey=()=>createHmac('sha256',secret).update('session').digest();
function ticket(){const payload=`${Date.now()+7*864e5}.${randomBytes(24).toString('hex')}`;const tag=createHmac('sha256',sessionKey()).update(payload).digest('hex');return `${payload}.${tag}`}
function authorized(req){const m=(req.headers.cookie||'').match(/(?:^|;\s*)session=([^;]+)/);if(!m)return false;const value=m[1];const parts=value.split('.');if(parts.length!==3||Number(parts[0])<Date.now())return false;const body=parts.slice(0,2).join('.'),expected=createHmac('sha256',sessionKey()).update(body).digest('hex');return expected.length===parts[2].length&&timingSafeEqual(Buffer.from(expected),Buffer.from(parts[2]))}
function json(res,code,data){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data))}
function fail(code,message){const e=new Error(message);e.status=code;throw e}
async function body(req,max=8e6){let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>max)fail(413,'データが大きすぎます');chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}catch{fail(400,'JSONを確認してください')}}
function requireAccount(id){const a=row('SELECT * FROM accounts WHERE id=?',id);if(!a)fail(404,'アカウントが見つかりません');return a}
const categories=new Set(['purikura','bereal','selfie','mirror','candid']);
function imageBytes(input){const m=/^data:(image\/(?:jpeg|png|webp));base64,([A-Za-z0-9+/=]+)$/.exec(input||'');if(!m)fail(400,'JPEG・PNG・WebP画像を選択してください');const buf=Buffer.from(m[2],'base64');if(!buf.length||buf.length>5*1024*1024)fail(413,'画像は5MB以下にしてください');const real=(buf[0]===0xff&&buf[1]===0xd8)?'image/jpeg':(buf[0]===0x89&&buf[1]===0x50)?'image/png':(buf.toString('ascii',0,4)==='RIFF'&&buf.toString('ascii',8,12)==='WEBP')?'image/webp':null;if(real!==m[1])fail(400,'画像データが不正です');return {buf,mime:real}}
async function addAsset({data,kind,category,accountId,name}){const {buf,mime}=imageBytes(data);const id=uid(),filename=id+({'image/png':'.png','image/jpeg':'.jpg','image/webp':'.webp'}[mime]);await writeFile(join(dataDir,'assets',filename),buf,{mode:0o600,flag:'wx'});run('INSERT INTO assets(id,kind,category,account_id,name,mime,filename) VALUES(?,?,?,?,?,?,?)',id,kind,category||null,accountId||null,name||'',mime,filename);return id}
function addJob(accountId,kind,work){const id=uid();run("INSERT INTO jobs(id,account_id,kind,status) VALUES(?,?,?,'running')",id,accountId,kind);Promise.resolve().then(work).then(detail=>run("UPDATE jobs SET status='done',detail=?,updated_at=datetime('now') WHERE id=?",String(detail||''),id)).catch(e=>{console.error(`${kind}:`,e);run("UPDATE jobs SET status='failed',detail=?,updated_at=datetime('now') WHERE id=?",String(e.message||e).slice(0,500),id)});return id}
run("UPDATE jobs SET status='failed',detail='サーバー再起動により処理が中断しました',updated_at=datetime('now') WHERE status='running'");
async function generateBatch(a,count){
 const refs=all("SELECT * FROM refs WHERE summary<>'' ORDER BY fetched_at DESC LIMIT 8");
 const history=all('SELECT text FROM drafts WHERE account_id=? ORDER BY created_at DESC LIMIT 30',a.id);
 const posts=await ai.generateWeek(a,refs,history,new Date().toISOString(),count);
 db.exec('BEGIN');const ids=[];
 try{for(const p of posts){const id=uid(),prompt=ai.imagePrompt(a,p,all("SELECT * FROM assets WHERE kind='style' ORDER BY created_at DESC"));run('INSERT INTO drafts(id,account_id,text,image_style,scheduled_at,image_prompt) VALUES(?,?,?,?,?,?)',id,a.id,p.text,p.image_style,p.scheduled_at,prompt);ids.push(id)}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}
 if(a.auto_approve){for(const id of ids){const d=row('SELECT * FROM drafts WHERE id=?',id);try{
   if(d.image_style)continue;
   if(new Date(d.scheduled_at).getTime()<Date.now()+60000)throw Error('予定日時を過ぎました');
   run("UPDATE drafts SET status='scheduled',updated_at=datetime('now') WHERE id=?",id);
  }catch(e){run("UPDATE drafts SET status='needs_review',error=? WHERE id=?",String(e.message||e).slice(0,500),id)}}}
 return `${posts.length}件の投稿案を保存${a.auto_approve?'（自動承認を適用）':''}`;
}
 async function publishDue(){const due=all("SELECT * FROM drafts WHERE status='scheduled' AND scheduled_at<=? ORDER BY scheduled_at LIMIT 5",new Date().toISOString());for(const d of due){const a=requireAccount(d.account_id);if(!a.enabled||!a.session_cipher)continue;const claim=run("UPDATE drafts SET status='publishing',attempt_count=attempt_count+1,updated_at=datetime('now') WHERE id=? AND status='scheduled'",d.id);if(!claim.changes)continue;try{const asset=d.image_id?row('SELECT * FROM assets WHERE id=?',d.image_id):null;if(d.image_style&&!asset)throw Error('投稿画像がありません。画像を再設定してください');const cookies=decrypt(a.session_cipher);await x.checkBio(cookies,a.username);const xId=await x.publish(cookies,d.text,asset&&join(dataDir,'assets',asset.filename),`架空AIキャラクター ${a.character_name} の生成画像`);run("UPDATE drafts SET status='posted',x_post_id=?,posted_at=datetime('now'),error=NULL,updated_at=datetime('now') WHERE id=?",xId,d.id)}catch(e){console.error('publish:',e);run("UPDATE drafts SET status='failed',error=?,updated_at=datetime('now') WHERE id=?",String(e.message||e).slice(0,500),d.id)}}}
function replenish(){if(!process.env.GEMINI_API_KEY)return;for(const a of all('SELECT * FROM accounts WHERE enabled=1 AND session_cipher IS NOT NULL')){
 const recent=row("SELECT id FROM jobs WHERE account_id=? AND kind='auto-weekly-plan' AND created_at>=datetime('now','-6 days') ORDER BY created_at DESC LIMIT 1",a.id);
 if(recent)continue;
 const pending=row("SELECT count(*) n FROM drafts WHERE account_id=? AND created_at>=datetime('now','-6 days')",a.id)?.n||0;
 if(pending>=Number(a.posting_frequency||7))continue;
 addJob(a.id,'auto-weekly-plan',()=>generateBatch(a,Math.min(21,Math.max(1,Number(a.posting_frequency)||7))));
}}
// Interrupted in-flight requests stay 'publishing': an ambiguous response must never auto-post twice.
await mkdir(join(dataDir,'assets'),{recursive:true,mode:0o700});
let busy=false;async function tick(){if(busy)return;busy=true;try{replenish();await publishDue()}catch(e){console.error('scheduler:',e)}finally{busy=false}}
setInterval(tick,30000).unref();
setTimeout(tick,1000).unref();
const staticFiles={'/':['public/index.html','text/html'],'/app.js':['public/app.js','text/javascript'],'/style.css':['public/style.css','text/css'],'/favicon.svg':['public/favicon.svg','image/svg+xml']};
const server=http.createServer(async(req,res)=>{try{
 const path=new URL(req.url,'http://localhost').pathname,method=req.method;
 res.setHeader('x-frame-options','DENY');res.setHeader('referrer-policy','no-referrer');res.setHeader('content-security-policy',"default-src 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; base-uri 'none'; form-action 'self'");
 if(method==='GET'&&staticFiles[path]){const [f,type]=staticFiles[path];res.writeHead(200,{'content-type':`${type}; charset=utf-8`,'cache-control':'no-store'});return res.end(await readFile(f))}
 if(method==='GET'&&path==='/api/auth')return json(res,200,{authenticated:authorized(req)});
 if(method==='POST'&&path==='/api/login'){if(req.headers.origin&&new URL(req.headers.origin).host!==req.headers.host)fail(403,'送信元を確認してください');const attempt=limitLogin(req.socket.remoteAddress||'unknown');if(attempt.count>=8)fail(429,'時間を空けてから試してください');const b=await body(req,1024);const aa=scryptSync(String(b.password||''),'fixed-auth-verifier',32),bb=scryptSync(password,'fixed-auth-verifier',32);if(!timingSafeEqual(aa,bb)){attempt.count++;fail(401,'パスワードが違います')}attempt.count=0;res.setHeader('Set-Cookie',`session=${ticket()}; HttpOnly; SameSite=Strict; Path=/; Max-Age=604800${req.socket.encrypted||req.headers['x-forwarded-proto']==='https'?'; Secure':''}`);return json(res,200,{ok:true})}
 if(!authorized(req))fail(401,'ログインしてください');
 if(method!=='GET'){const origin=req.headers.origin,hostHeader=req.headers.host;if(origin&&new URL(origin).host!==hostHeader)fail(403,'送信元を確認してください')}
 if(method==='POST'&&path==='/api/logout'){res.setHeader('Set-Cookie','session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true})}
 if(method==='GET'&&path==='/api/state'){return json(res,200,{accounts:all('SELECT * FROM accounts ORDER BY created_at DESC').map(publicAccount),refs:all('SELECT * FROM refs ORDER BY created_at DESC'),assets:all('SELECT id,kind,category,account_id,name,mime,created_at FROM assets ORDER BY created_at DESC'),drafts:all('SELECT * FROM drafts ORDER BY scheduled_at DESC,created_at DESC LIMIT 500'),jobs:all('SELECT * FROM jobs ORDER BY created_at DESC LIMIT 30'),configured:!!process.env.GEMINI_API_KEY})}
 if(method==='GET'&&path.startsWith('/api/assets/')){const asset=row('SELECT * FROM assets WHERE id=?',path.slice(12));if(!asset)fail(404,'画像なし');const download=new URL(req.url,'http://localhost').searchParams.has('download');res.writeHead(200,{'content-type':asset.mime,'cache-control':'private, max-age=300','x-content-type-options':'nosniff',...(download?{'content-disposition':`attachment; filename="${asset.filename}"`}:{})});return res.end(await readFile(join(dataDir,'assets',asset.filename)))}
 if(method==='POST'&&path==='/api/accounts'){const b=await body(req),username=String(b.username||'').replace(/^@/,'').trim();if(!/^[A-Za-z0-9_]{1,15}$/.test(username))fail(400,'XのIDを確認してください');const id=uid();run('INSERT INTO accounts(id,username,display_name,character_name,bio) VALUES(?,?,?,?,?)',id,username,String(b.display_name||username).slice(0,80),String(b.character_name||b.display_name||username).slice(0,80),`架空のAIキャラクター｜${String(b.character_name||username).slice(0,60)}`);return json(res,201,{id})}
 let m=path.match(/^\/api\/accounts\/([^/]+)$/);
 if(m&&method==='PATCH'){const current=requireAccount(m[1]);const b=await body(req);const keys=['display_name','character_name','age','location','tone','personality','hobbies','bio','emoji_style','ng_topics','posting_frequency','active_hours','enabled','auto_approve'];const values=Object.fromEntries(keys.filter(k=>Object.hasOwn(b,k)).map(k=>[k,b[k]]));if(Object.hasOwn(values,'enabled'))values.enabled=values.enabled===true?1:0;if(Object.hasOwn(values,'auto_approve'))values.auto_approve=values.auto_approve===true?1:0;if(!/AI/i.test(String(values.bio??current.bio))||!/(架空|バーチャル)/.test(String(values.bio??current.bio)))fail(400,'プロフィールに架空のAIキャラクターである旨を記載してください');if(String(values.bio??current.bio).length>160)fail(400,'プロフィールは160文字以内にしてください');if(values.age!=null&&values.age<18)fail(400,'キャラクターの年齢は18歳以上にしてください');if(values.enabled&&!current.session_cipher)fail(400,'先にX接続をしてください');if(values.auto_approve&&!(values.enabled??current.enabled))fail(400,'自動承認には運用ONが必要です');if(!Object.keys(values).length)fail(400,'変更項目がありません');if(values.bio!=null&&values.bio!==current.bio&&current.session_cipher){try{await x.ensureBio(decrypt(current.session_cipher),current.username,String(values.bio))}catch(e){fail(502,'Xプロフィールを更新できませんでした: '+e.message)}}run(`UPDATE accounts SET ${Object.keys(values).map(k=>k+'=?').join(',')},updated_at=datetime('now') WHERE id=?`,...Object.values(values).map(v=>v??''),m[1]);return json(res,200,{ok:true})}
 if(m&&method==='DELETE'){requireAccount(m[1]);db.exec('BEGIN');try{run('DELETE FROM drafts WHERE account_id=?',m[1]);run('DELETE FROM accounts WHERE id=?',m[1]);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return json(res,200,{ok:true})}
 m=path.match(/^\/api\/accounts\/([^/]+)\/connect$/);
 if(m&&method==='POST'){const a=requireAccount(m[1]),b=await body(req,4096);let result;try{if(b.cookies){result={cookies:String(b.cookies),who:await x.verify(String(b.cookies))}}else if(b.password){result=await x.login(a.username,String(b.password),String(b.email||''))}else fail(400,'ログイン情報を入力してください')}catch(e){if(e.status)throw e;fail(502,'Xログインに失敗しました: '+String(e.message||e).slice(0,220))}if(result.who?.username?.toLowerCase()!==a.username.toLowerCase())fail(400,`接続先が @${a.username} ではありません`);try{await x.ensureBio(result.cookies,a.username,a.bio)}catch(e){fail(502,'XプロフィールのAI表記を設定できませんでした: '+e.message)}run("UPDATE accounts SET session_cipher=?,session_status='connected',updated_at=datetime('now') WHERE id=?",encrypt(result.cookies),a.id);return json(res,200,{username:a.username})}
 m=path.match(/^\/api\/accounts\/([^/]+)\/disconnect$/);
 if(m&&method==='POST'){requireAccount(m[1]);run("UPDATE accounts SET session_cipher=NULL,enabled=0,session_status='unconnected' WHERE id=?",m[1]);return json(res,200,{ok:true})}
 if(method==='POST'&&path==='/api/refs'){const b=await body(req),username=String(b.username||'').replace(/^@/,'').trim();if(!/^[A-Za-z0-9_]{1,15}$/.test(username))fail(400,'IDを確認してください');const id=uid();run('INSERT INTO refs(id,username) VALUES(?,?)',id,username);return json(res,201,{id})}
 m=path.match(/^\/api\/refs\/([^/]+)$/);
 if(m&&method==='DELETE'){run('DELETE FROM refs WHERE id=?',m[1]);return json(res,200,{ok:true})}
 m=path.match(/^\/api\/refs\/([^/]+)\/fetch$/);
 if(m&&method==='POST'){const ref=row('SELECT * FROM refs WHERE id=?',m[1]);if(!ref)fail(404,'参考アカウントがありません');const b=await body(req),a=requireAccount(b.account_id);if(!a.session_cipher)fail(400,'取得用のXアカウントを接続してください');const limit=Math.min(5000,Math.max(20,Number(b.limit)||500));const job=addJob(a.id,'fetch',async()=>{const {profile,posts}=await x.collect(decrypt(a.session_cipher),ref.username,limit);const insert=db.prepare('INSERT OR REPLACE INTO ref_posts(id,ref_id,text,posted_at,metrics_json,media_json) VALUES(?,?,?,?,?,?)');db.exec('BEGIN');try{for(const p of posts)if(p.id&&p.text)insert.run(p.id,ref.id,p.text,p.createdAt||null,JSON.stringify(p.metrics||{}),JSON.stringify(p.media||[]));run("UPDATE refs SET display_name=?,account_id=?,fetched_at=datetime('now') WHERE id=?",profile.name||ref.username,a.id,ref.id);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return `${posts.length}件取得`});return json(res,202,{job})}
 m=path.match(/^\/api\/refs\/([^/]+)\/analyze$/);
 if(m&&method==='POST'){const ref=row('SELECT * FROM refs WHERE id=?',m[1]);if(!ref)fail(404,'参考アカウントがありません');const posts=all('SELECT * FROM ref_posts WHERE ref_id=? ORDER BY posted_at DESC LIMIT 120',ref.id);if(!posts.length)fail(400,'先に投稿を取得してください');const job=addJob(null,'analyze',async()=>{const summary=await ai.analyze(ref,posts);run('UPDATE refs SET summary=? WHERE id=?',summary,ref.id);return '分析完了'});return json(res,202,{job})}
 if(method==='GET'&&path==='/api/ref-posts'){const refId=new URL(req.url,'http://localhost').searchParams.get('ref_id');return json(res,200,{posts:all('SELECT * FROM ref_posts WHERE ref_id=? ORDER BY posted_at DESC LIMIT 500',refId||'')})}
 if(method==='POST'&&path==='/api/assets'){const b=await body(req),kind=b.kind==='base'?'base':'style';if(kind==='style'&&!categories.has(b.category))fail(400,'画像カテゴリを選択してください');if(kind==='base'&&!b.account_id)fail(400,'キャラクターを選択してください');if(b.account_id)requireAccount(b.account_id);const id=await addAsset({data:b.data,kind,category:kind==='style'?b.category:null,accountId:kind==='base'?b.account_id:null,name:String(b.name||'').slice(0,100)});return json(res,201,{id})}
 if(method==='POST'&&path==='/api/drafts/images/bulk'){
  const b=await body(req,72e6),items=b.items;
  if(!Array.isArray(items)||!items.length||items.length>10)fail(400,'一度に1〜10枚を選択してください');
  const targets=new Set();
  for(const item of items){if(!item||targets.has(item.draft_id))fail(400,'同じ投稿への重複指定はできません');targets.add(item.draft_id);const d=row('SELECT * FROM drafts WHERE id=?',item.draft_id);if(!d||!d.image_style||d.status!=='needs_review')fail(409,'画像待ちのレビュー投稿を指定してください');imageBytes(item.data)}
  const files=[];db.exec('BEGIN');
  try{for(const item of items){const id=await addAsset({data:item.data,kind:'style',category:'uploaded',accountId:null,name:String(item.name||'投稿画像').slice(0,100)});files.push(row('SELECT filename FROM assets WHERE id=?',id).filename);run("UPDATE drafts SET image_id=?,error=NULL,updated_at=datetime('now') WHERE id=?",id,item.draft_id)}db.exec('COMMIT')}
  catch(e){db.exec('ROLLBACK');await Promise.all(files.map(f=>unlink(join(dataDir,'assets',f)).catch(()=>{})));throw e}
  return json(res,201,{count:items.length});
 }
 m=path.match(/^\/api\/assets\/([^/]+)$/);
 if(m&&method==='DELETE'){const a=row('SELECT * FROM assets WHERE id=?',m[1]);if(!a)fail(404,'画像なし');run('DELETE FROM assets WHERE id=?',a.id);await unlink(join(dataDir,'assets',a.filename)).catch(()=>{});return json(res,200,{ok:true})}
 if(method==='POST'&&path==='/api/generate-week'){const b=await body(req),a=requireAccount(b.account_id);const count=Math.min(21,Math.max(1,Number(b.count)||Number(a.posting_frequency)||7));const job=addJob(a.id,'weekly-plan',()=>generateBatch(a,count));return json(res,202,{job})}
 if(method==='POST'&&path==='/api/drafts'){const b=await body(req),a=requireAccount(b.account_id);if(!String(b.text||'').trim()||String(b.text).length>280)fail(400,'投稿文を280文字以内で入力してください');const id=uid(),style=categories.has(b.image_style)?b.image_style:null,text=String(b.text).trim();run('INSERT INTO drafts(id,account_id,text,scheduled_at,image_style,image_prompt) VALUES(?,?,?,?,?,?)',id,b.account_id,text,b.scheduled_at||null,style,ai.imagePrompt(a,{text,image_style:style},all("SELECT * FROM assets WHERE kind='style' ORDER BY created_at DESC")));return json(res,201,{id})}
 m=path.match(/^\/api\/drafts\/([^/]+)$/);
 if(m&&method==='PATCH'){const d=row('SELECT * FROM drafts WHERE id=?',m[1]);if(!d)fail(404,'投稿なし');if(d.status!=='needs_review'&&d.status!=='scheduled')fail(409,'先に投稿状況を確認してください');const b=await body(req),allowed=['text','scheduled_at','image_style','image_prompt'];const changes=Object.fromEntries(allowed.filter(k=>Object.hasOwn(b,k)).map(k=>[k,b[k]]));if(changes.text!=null&&(!String(changes.text).trim()||String(changes.text).length>280))fail(400,'投稿文を280文字以内で入力してください');if(changes.image_style&&!categories.has(changes.image_style))fail(400,'画像カテゴリが不正です');if(changes.image_prompt!=null&&String(changes.image_prompt).length>5000)fail(400,'画像プロンプトは5000文字以内にしてください');if(Object.hasOwn(changes,'image_style')&&!changes.image_style){changes.image_style=null;changes.image_id=null;changes.image_prompt=''}else if((Object.hasOwn(changes,'text')||Object.hasOwn(changes,'image_style'))&&!Object.hasOwn(changes,'image_prompt'))changes.image_prompt=ai.imagePrompt(requireAccount(d.account_id),{...d,...changes},all("SELECT * FROM assets WHERE kind='style' ORDER BY created_at DESC"));if(!Object.keys(changes).length)fail(400,'変更項目がありません');run(`UPDATE drafts SET ${Object.keys(changes).map(k=>`${k}=?`).join(',')},status='needs_review',error=NULL,updated_at=datetime('now') WHERE id=?`,...Object.values(changes),d.id);return json(res,200,{ok:true})}
 if(m&&method==='DELETE'){const d=row('SELECT * FROM drafts WHERE id=?',m[1]);if(!d)fail(404,'投稿なし');if(d.status!=='needs_review'&&d.status!=='scheduled')fail(409,'先に投稿状況を確認してください');run('DELETE FROM drafts WHERE id=?',d.id);return json(res,200,{ok:true})}
 m=path.match(/^\/api\/drafts\/([^/]+)\/schedule$/);
 if(m&&method==='POST'){const d=row('SELECT * FROM drafts WHERE id=?',m[1]);if(!d)fail(404,'投稿なし');const b=await body(req),a=requireAccount(d.account_id);if(!a.session_cipher||!a.enabled)fail(400,'X接続と運用ONが必要です');const date=new Date(b.scheduled_at||d.scheduled_at);if(!Number.isFinite(date.getTime())||date.getTime()<Date.now()+60000)fail(400,'予約日時は1分以上先にしてください');if(d.image_style&&!d.image_id)fail(400,'先に画像を生成・選択してください');if(d.status!=='needs_review')fail(409,'予約できない状態です');run("UPDATE drafts SET status='scheduled',scheduled_at=?,error=NULL,updated_at=datetime('now') WHERE id=?",date.toISOString(),d.id);return json(res,200,{ok:true})}
 m=path.match(/^\/api\/drafts\/([^/]+)\/unschedule$/);
 if(m&&method==='POST'){const result=run("UPDATE drafts SET status='needs_review',updated_at=datetime('now') WHERE id=? AND status='scheduled'",m[1]);if(!result.changes)fail(409,'予約を解除できません');return json(res,200,{ok:true})}
 m=path.match(/^\/api\/drafts\/([^/]+)\/resolve$/);
 if(m&&method==='POST'){const d=row('SELECT * FROM drafts WHERE id=?',m[1]);if(!d||!['failed','publishing'].includes(d.status))fail(409,'確認対象の投稿ではありません');const b=await body(req);if(b.outcome==='posted'){if(!/^\d{10,25}$/.test(String(b.x_post_id||'')))fail(400,'Xの投稿IDを入力してください');run("UPDATE drafts SET status='posted',x_post_id=?,posted_at=datetime('now'),error=NULL WHERE id=?",String(b.x_post_id),d.id)}else if(b.outcome==='not_posted'){run("UPDATE drafts SET status='needs_review',scheduled_at=NULL,error=NULL WHERE id=?",d.id)}else fail(400,'X上の投稿状況を選択してください');return json(res,200,{ok:true})}
 m=path.match(/^\/api\/drafts\/([^/]+)\/image$/);
 if(m&&method==='POST')fail(400,'画像は手元で生成してからアップロードしてください');
 if(method==='GET'&&path==='/api/health')return json(res,200,{ok:true});
 fail(404,'ページが見つかりません');
 }catch(e){console.error(req.method,req.url,e);json(res,e.status||500,{error:e.status?e.message:'処理に失敗しました。サーバーログを確認してください'})}});
server.listen(port,host,()=>console.log(`X-Nekama: http://${host}:${port}`));
