"""Generate the Worker payload embedded in the standalone tweak."""
import json
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
target = Path(sys.argv[1]) if len(sys.argv) > 1 else root.parent / "riri-tweak"
target.joinpath("RiriWorkerSource.h").write_text(
    "// Generated by riri-cloudflare/tools/embed.py; do not edit.\n"
    + "#define RIRI_WORKER_SOURCE " + json.dumps(root.joinpath("worker.mjs").read_text(), ensure_ascii=False) + "\n"
    + "#define RIRI_SCHEMA_SOURCE " + json.dumps(root.joinpath("schema.sql").read_text(), ensure_ascii=False) + "\n"
)
